dist: focal
language: python
python:
- '3.9'
addons:
  postgresql: '13'
services:
- postgresql
env:
- DJANGO=3.2 DB=postgres
install:
- pipenv install
before_script:
- psql -c "CREATE DATABASE WFD_TEST;" -U postgres
- psql -c "CREATE USER ci_agent PASSWORD 'ciAgent';" -U postgres
- psql -c "ALTER USER ci_agent CREATEDB;" -U postgres
- psql -c "GRANT ALL PRIVILEGES on DATABASE WFD_TEST to ci_agent;" -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: rcRmibb199PK7vWAE5OtqB7gdazPzaw2QtoLIgCMxIW35KTvC7/o/0JxuTqOCGnPZNGeXwq9bpi9+JJNcKKwyMR2a7Pm2+Z72yFRdzyNBAJGFkr+UN3YMtUQ4/1S9wnDIRJVH5fqzrobHLt8SCusH87RnlRLJGcwTjWGAEpiFK3fupzEQFkH2/4zL5Zd9PB9Nm1WKZh0ccIx970kJ5/Gh7VubYfqghVVl+5tX158bCgFVmI5Dsu9I/UAX9KVnfdBU7hX/LcadshoSYzQMOg2hIjHpnZ9HFgZq3PWPaT34CosRKforj2YXTF7TUWZWv8yWpL73MGci+5m9XMSdxoswyvKQup08i4wV/gQEyUzhmqUPDM6YlyGnyHjxC1nuih2yILbCZA7ShIsA9jP01EvBfbsMq0jbp50iETkSCZEGT04BLZbfUbeoQU3AbUOaWGHu5ChnUBT57+auhy0sp2fhaFRbnJqkLHGDlPKZQ+GatnICN4hIPRvdHDMoWehDTCmolmWibAvDy7S1j+QRi8ZVtVYr3LsfWGSzn4h/auTTro17Jgc8Y1klTs+Ol2lZEP3EVfRWlAkZ99eyaaiO8gHQib5wCCkR2qyYnFeY8Nac77hqg47ptz8/qwtXM0yZ7W3GR+XRhPkGffggFY33tYI+fahkcEjg7likSmYIFJRgBg=
  app: vite-une-recette
  on:
    branch: release-heroku