dist: focal
language: python
python:
  - "3.9"
addons:
  postgresql: "13"
services:
  - postgresql
env:
  - DJANGO=3.2 DB=postgres
# command to install dependencies
install:
  - echo '51.159.66.3 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEJvni8bHhCiUhO6TgrFoceKVJE7he9QwNUW8EyY2NSoxzxn0Rv29GmSYV0wTBGxWPuP7nwVVdPrwFPOyNZmDSk=' >> $HOME/.ssh/known_hosts
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE WFD_TEST;" -U postgres
  - psql -c "CREATE USER ci_agent PASSWORD 'ciAgent';" -U postgres
  - psql -c "ALTER USER ci_agent CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE WFD_TEST to ci_agent;" -U postgres
# command to run tests
script:
  - python manage.py test
# commands for deployment
before_deploy:
  - python manage.py collectstatic
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet /home/travis/build/slesouef/Whats-for-diner slesouef@51.159.66.3:~/django-web/
  on:
    branch: release/production