dist: focal
language: python
python:
- '3.9'
addons:
  postgresql: '13'
services:
- postgresql
env:
- DJANGO=3.2 DB=postgres
install:
- pipenv install
before_script:
- psql -c "CREATE DATABASE WFD_TEST;" -U postgres
- psql -c "CREATE USER ci_agent PASSWORD 'ciAgent';" -U postgres
- psql -c "ALTER USER ci_agent CREATEDB;" -U postgres
- psql -c "GRANT ALL PRIVILEGES on DATABASE WFD_TEST to ci_agent;" -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: avkh0/FK2NriNDY+MLphXs8QvVuwQMLCFbe8ev/rZGDwR9APG4Xp5AajQaWWozPGAjjL1InbyiHOpTbayw9Ke1S4FjzuYU9CkKLXKWgVVm+ICBUvq2SFDkED//Frag7IeFLI7Dt1XcvzjxCNzvH2P/hz5Zgai8EuKlgpvLPPFpNxI84aKeLZplK/CTJCC8J4ncUFPEqdOAYC2p/GQKLwNDsE/GZ67wHF9jJG2wERR2wkxTk9X99+MjBTomsJzE9BFF3iHEZYFN8a7SDealkNsuEAqCjO2DbExCLlo6FFi6VupMHjRRJmZl4Oam7xtQreZ/lHOIwVZjGdLPYBAIL9jkgTqQCLSIK+r3gzDw5U81I58JfBSrre9hQBJWdr8O82VSJlhjv3NJr/4j1Z9koXE2X4Hztz6EpTC4vZFLRfY7BcJ64qUkulzqRWtcnGspcGlQE/7rUPhl65h/B7aAsj4ZeZfjifnwvc6IBbzg417+zAMxACQcpUaLmq+B3NzSUnWrE5w5B4Lj/gRov+s0H11vOeFSOxYzZyWsK7jDdPtbMPyf2DY25IisaEBRmZYs26NmDn+QFrIfaP2xKjteO+6xfLnimcJ+U9aDczguulUXqCGd9xPrvWi2+SqmPVTjET65b6W/JemJ7i0UD4+yavRQLQkQeIHcdjb/O5bDDeT/Y=
  app: vite-une-recette
  on:
    repo: slesouef/Whats-for-diner
    branch: release-heroku
  skip_cleanup: 'true'
