dist: focal
language: python
python:
  - "3.9"
services:
  - postgresql
env:
  - DB=postgres
# command to install dependencies
install:
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER ciAgent PASSWORD 'ciAgent';" -U postgres
  - psql -c "ALTER USER ciAgent CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE test to ciAgent;" -U postgres
# command to run tests
script:
  - python manage.py test