dist: focal
language: python
python:
  - "3.9"
addons:
  postgresql: "13"
services:
  - postgresql
env:
  - DJANGO=3.2 DB=postgres
# command to install dependencies
install:
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE WFD_TEST;" -U postgres
  - psql -c "CREATE USER ci_agent PASSWORD 'ciAgent';" -U postgres
  - psql -c "ALTER USER ci_agent CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE WFD_TEST to ci_agent;" -U postgres
# command to run tests
script:
  - python manage.py test